/**
 * Device-frame bezel assets for UI mode + the trace viewer.
 *
 * These PNGs are real photographic device frames (with a transparent screen
 * window) extracted once from the bezel.fit API — see scripts/fetch-bezels.mjs.
 * They are imported here so Vite inlines them into the single-file builds; the
 * bezel.fit API is never called at runtime. Re-run the script to regenerate the
 * assets, then paste its printed metadata into FRAMES below.
 *
 * bezel.fit only ships phone frames, so there is one generic frame per platform.
 * It covers every iOS / Android phone; tablets and odd-aspect devices fall back
 * to the CSS bezels (see ui-mode.css.ts `.dm-skin-*`).
 */

import type { DevicePlatform, DeviceFormFactor } from '../../ui-protocol.js';
import iphoneFrame from './iphone.png';
import androidFrame from './android.png';

/** Screen window within a frame image, as fractions of the frame's width/height. */
export interface ScreenRect {
  leftPct: number
  topPct: number
  widthPct: number
  heightPct: number
}

export interface DeviceFrame {
  /** Inlined data URI of the frame PNG (transparent screen window). */
  src: string
  /** width / height of the full frame image. */
  frameAspect: number
  /** Where the device screen sits inside the frame. */
  screen: ScreenRect
  /** width / height of the screen window — used to reject mismatched devices. */
  screenAspect: number
  /** Screen corner radius as a percentage of the screen window width, so the
   * content can be clipped to match the bezel's rounded opening. */
  screenRadiusPct: number
}

function frame(src: string, frameAspect: number, screen: ScreenRect, screenRadiusPct: number): DeviceFrame {
  return {
    src,
    frameAspect,
    screen,
    screenAspect: (screen.widthPct / screen.heightPct) * frameAspect,
    screenRadiusPct,
  };
}

// ─── Generated by scripts/fetch-bezels.mjs (bezel.fit) ───
const FRAMES: Partial<Record<DevicePlatform, DeviceFrame>> = {
  ios: frame(iphoneFrame, 0.4895, { leftPct: 0.0533, topPct: 0.025, widthPct: 0.8935, heightPct: 0.95 }, 16),
  android: frame(androidFrame, 0.4751, { leftPct: 0.0418, topPct: 0.0202, widthPct: 0.9078, heightPct: 0.9623 }, 14),
};

/**
 * How far a device's screen aspect ratio may differ from a frame's screen
 * window before we fall back to CSS. Modern phones (X–17, most Androids:
 * ≈0.45–0.50) stay within tolerance of the ≈0.46 frames; squarer devices
 * (iPhone SE 0.56, iPads, tablets) fall back so they aren't stretched.
 */
const ASPECT_TOLERANCE = 0.18;

/**
 * Pick the photographic frame for a device, or undefined to use the CSS bezel.
 *
 * @param platform     iOS / Android (required — no platform ⇒ no frame).
 * @param formFactor   When 'tablet', always falls back to CSS (no tablet frames).
 * @param contentAspect Screen/screenshot width÷height. When provided, the frame
 *                      is rejected if its screen window is too different a shape,
 *                      which also catches tablets when formFactor is unknown.
 */
export function selectDeviceFrame(opts: {
  platform?: DevicePlatform
  formFactor?: DeviceFormFactor
  contentAspect?: number
}): DeviceFrame | undefined {
  const { platform, formFactor, contentAspect } = opts;
  if (!platform || formFactor === 'tablet') return undefined;
  const f = FRAMES[platform];
  if (!f) return undefined;
  if (contentAspect && contentAspect > 0) {
    if (Math.abs(contentAspect / f.screenAspect - 1) > ASPECT_TOLERANCE) return undefined;
  }
  return f;
}

/** Inline style placing an element over a frame's screen window, and exposing
 * the screen corner radius (--dm-sr, in cqi units of the screen box). */
export function screenWindowStyle(frame: DeviceFrame): Record<string, string> {
  const { screen } = frame;
  return {
    left: `${(screen.leftPct * 100).toFixed(3)}%`,
    top: `${(screen.topPct * 100).toFixed(3)}%`,
    width: `${(screen.widthPct * 100).toFixed(3)}%`,
    height: `${(screen.heightPct * 100).toFixed(3)}%`,
    '--dm-sr': String(frame.screenRadiusPct),
  };
}
